context:
  name: Yash
  version: "2.59"
  author: magicant

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ author }}/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: efe9d299a14d103d259b8a709fa2b664d8ff6ee498523f797f31f67db62e11af

build:
  number: 0
  skip:
    - win
  script:
    - ./configure --prefix="${{ PREFIX }}"
    - make install-binary -j${{ CPU_COUNT }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - make
  host:
    - if: osx
      then: libintl-devel
    - ncurses

tests:
  - script:
      - test "$(yash -c 'echo Hello, Yash')" = "Hello, Yash"

about:
  homepage: https://magicant.github.io/yash
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Yet another shell
  description: |
    Yash, yet another shell, is a POSIX-compliant command line shell written in C99 (ISO/IEC 9899:1999).
    Yash is intended to be the most POSIX-compliant shell in the world while supporting features for daily interactive and scripting use.
    Notable features are:
      - Global aliases
      - Arrays
      - Socket redirection, pipeline redirection, and process redirection
      - Brace expansion and extended globbing
      - Fractional numbers in arithmetic expansion
      - Prompt command and command-not-found handler
      - Command line completion with predefined completion scripts for more than 100 commands
      - Command line prediction based on command history
  repository: https://github.com/magicant/yash
  documentation: https://magicant.github.io/yash/doc

extra:
  recipe-maintainers:
    - eunos-1128
